### ISSUE TITLE
Can Soft Impute be used for non-numeric part of a dataset?

### ISSUE THREAD

**Issue by ambareeshsrja16** [iskandr/fancyimpute#103]
Can Soft Impute be used for values other than numeric? Say Categorical (e.g - Race, Sex, Marital Status etc) Some imputation procedures do this by replacing the categorical variables with a dummy variable that takes numeric values (say Male - 2, Female - 1, Other- 0) and perform imputation. Does Soft Impute do something similar?

**Comment by sergeyf** [comment]
Gotta do your own numerical conversion - we don't do that for you.

**Comment by ambareeshsrja16** [comment]
Alright, thank you!
