### ISSUE TITLE
Why is ARPACK library used in place of PROPACK?

### ISSUE THREAD

**Issue by ambareeshsrja16** [iskandr/fancyimpute#104]
I am studying the paper "Regularization Algorithms for Learning Large Incomplete Matrices" by Mazumder, on which Soft-Impute is based. I was really glad to find a Python implementation for the same, thank you!

I had a question, in the _svd_step, randomized SVD (when full rank) and ARPACK are used (from scipy), even though the original paper mentions PROPACK. Is there any specific reason for this?

Thank you!

**Comment by sergeyf** [comment]
@iskandr wrote it so he'd know, but I guess we just used whatever is default and easy. Would it matter what package we used?

**Comment by ambareeshsrja16** [comment]
I'm not completely sure of this, but ARPACK may not be scalable to large matrices (which is why the paper uses PROPACK in all its results)

https://simplyml.com/benchmarking-the-singular-value-decomposition/ shows a benchmarking of all FORTRAN libraries, and PROPACK is much faster.

**Comment by sergeyf** [comment]
Cool. We're too busy to make any major changes, but feel free to submit + benchmarks a PR if you're inspired!

**Comment by ambareeshsrja16** [comment]
Alright, I will give it a shot! Thank you!

**Comment by sergeyf** [comment]
Any update here? Or should I close this issue?

**Comment by ambareeshsrja16** [comment]
I haven't gotten time to get around it yet! I'll re-open when I do! Thank you!
