### ISSUE TITLE
Not impute to 0 not_imputable data

### ISSUE THREAD

**Issue by fabrizioruffini** [iskandr/fancyimpute#106]
Dear Sir,
while using the fancyimpute package (many thanks for your work), I'd find appreciable if I could have the possibility not_to_set_to_zero the values that for some reason do not get filled by the algorithm.

Many thanks for your time
Best

**Comment by sergeyf** [comment]
Howdy. Sorry to say, but we're pretty much in maintenance mode and not really adding features.

**Comment by sergeyf** [comment]
Sure! We'd love to look at  PR.
