### ISSUE TITLE
Failure on Travis

### ISSUE THREAD

**Issue by iskandr** [iskandr/fancyimpute#109]
Seems to be at the deploy step?

```
NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: Invalid value for classifiers. Error: 'Development Status :: 3 - Beta' is not a valid choice for this field for url: https://upload.pypi.org/legacy/
```

**Comment by sergeyf** [comment]
Hahaha damn! I'll change it back to alpha =)

**Comment by sergeyf** [comment]
Fix is in #110. Hopefully that will make it stop complaining and we can go back to not doing anything for this package.

**Comment by sergeyf** [comment]
Ok it's merged. Lemme know if I need to do more stuff.

**Comment by iskandr** [comment]
All eyes on Travis

**Comment by iskandr** [comment]
Does TensorFlow just get chattier with each release?

**Comment by iskandr** [comment]
Green!

**Comment by sergeyf** [comment]
Mazel tov.
