### ISSUE TITLE
Unable to install fancyimpute via pip

### ISSUE THREAD

**Issue by yudai-patronai** [iskandr/fancyimpute#119]
Trying to install fancyimpute via command 
`pip install fancyimpute`
using Anaconda 3 on Arch Linux , i'm stably receiving the following:

`error: Command "gcc -pthread -shared -B /home/ariel/anaconda3/compiler_compat -L/home/ariel/anaconda3/lib -Wl,-rpath=/home/ariel/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/src/scsmodule.o build/temp.linux-x86_64-3.7/scs/src/rw.o build/temp.linux-x86_64-3.7/scs/src/scs.o build/temp.linux-x86_64-3.7/scs/src/normalize.o build/temp.linux-x86_64-3.7/scs/src/aa.o build/temp.linux-x86_64-3.7/scs/src/ctrlc.o build/temp.linux-x86_64-3.7/scs/src/cones.o build/temp.linux-x86_64-3.7/scs/src/scs_version.o build/temp.linux-x86_64-3.7/scs/src/linalg.o build/temp.linux-x86_64-3.7/scs/src/util.o build/temp.linux-x86_64-3.7/scs/linsys/common.o build/temp.linux-x86_64-3.7/scs/linsys/direct/private.o build/temp.linux-x86_64-3.7/scs/linsys/direct/external/amd/amd_control.o build/temp.linux-x86_64-3.7/scs/linsys/direct/external/amd/amd_order.o build/temp.linux-x86_64-3.7/scs/linsys/direct/external/amd/amd_dump.o build/temp.linux-x86_64-3.7/scs/linsys/direct/external/amd/amd_aat.o build/temp.linux-x86_64-3.7/scs/linsys/direct/external/amd/amd_2.o build/temp.linux-x86_64-3.7/scs/linsys/direct/external/amd/amd_valid.o build/temp.linux-x86_64-3.7/scs/linsys/direct/external/amd/amd_postorder.o build/temp.linux-x86_64-3.7/scs/linsys/direct/external/amd/amd_1.o build/temp.linux-x86_64-3.7/scs/linsys/direct/external/amd/amd_post_tree.o build/temp.linux-x86_64-3.7/scs/linsys/direct/external/amd/amd_defaults.o build/temp.linux-x86_64-3.7/scs/linsys/direct/external/amd/amd_preprocess.o build/temp.linux-x86_64-3.7/scs/linsys/direct/external/amd/amd_info.o build/temp.linux-x86_64-3.7/scs/linsys/direct/external/amd/amd_global.o build/temp.linux-x86_64-3.7/scs/linsys/direct/external/amd/SuiteSparse_config.o build/temp.linux-x86_64-3.7/scs/linsys/direct/external/qdldl/qdldl.o -L/home/ariel/anaconda3/lib -L/home/ariel/anaconda3/lib -lrt -lmkl_rt -lpthread -lmkl_rt -lpthread -o build/lib.linux-x86_64-3.7/_scs_direct.cpython-37m-x86_64-linux-gnu.so" failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ariel/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rzuqdq57/scs/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rzuqdq57/scs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-z3mqqqkk/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.`

Does it at all have an option to be installed with pip?

**Comment by hansen7** [comment]
Hi, there.

Of course it support install by pip, as you can see here:
https://pypi.org/project/fancyimpute/

And to more specific for you issues, please provide you error message, such as these:
https://github.com/wbolster/plyvel/issues/80
https://github.com/pySTEPS/pysteps/issues/37
