### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.impute'

### ISSUE THREAD

**Issue by Jessica-surina** [iskandr/fancyimpute#124]
i have tried in all the possible ways but it is showing error 
my code was:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(stratergy="median")

can you plz pt out the mistake ,it would be really helpful.
thanks in advance!

**Comment by sergeyf** [comment]
I think you're in the wrong repo. That's scikit-learn!

**Comment by Jessica-surina** [comment]
> I think you're in the wrong repo. That's scikit-learn!

Sorry I didn't get you?

**Comment by sergeyf** [comment]
This is the repo for `fancyimpute`. You're trying to import from `sklearn`. Questions about scikit-learn should be asked on their github repository.
