### ISSUE TITLE
ImportError: cannot import name 'logsumexp'

### ISSUE THREAD

**Issue by suparno89** [iskandr/fancyimpute#126]
I am trying to use the fancyimpute package and I constantly get the logsumexp import error no matter which imputer i try to import. I have scipy version **1.4.1**. I tried updating scipy and fancyimpute both with conda update but nothing helped. I got a suggestion to rollback scipy to 1.2.0 but I am afraid then some other stuff might break down with sklearn or so. I am wondering if there is a better solution. 
<img width="1050" alt="Screenshot 2020-05-29 at 12 09 36" src="https://user-images.githubusercontent.com/64039635/83248569-8c13b900-a1a5-11ea-9b67-59a7595a1d24.png">

**Comment by sergeyf** [comment]
Sigh, another CVXPY problem. Thanks for the report, I'll investigate.

**Comment by sergeyf** [comment]
What version of cvxpy do you have installed?

**Comment by suparno89** [comment]
0.4.10 

<img width="633" alt="Screenshot 2020-05-29 at 16 02 15" src="https://user-images.githubusercontent.com/64039635/83268380-d60c9700-a1c5-11ea-84f5-f231244a90df.png">

**Comment by sergeyf** [comment]
That's weird because our requirements file states that cvxpy has to be `cvxpy>=1.0.6`

Did you pip install fancyimpute?

**Comment by suparno89** [comment]
conda install -c brittainhard fancyimpute

as listed in the official conda website [here](https://anaconda.org/brittainhard/fancyimpute)

**Comment by sergeyf** [comment]
That was last updated ` Last upload: 2 years and 9 months ago `. 

Please don't use conda - we don't support it.

If you just do `pip install fancyimpute` it will work fine.

**Comment by suparno89** [comment]
solved

**Comment by suparno89** [comment]
thanks a lot.
