### ISSUE TITLE
unable to install package cvxpy

### ISSUE THREAD

**Issue by tangtangsiqi** [iskandr/fancyimpute#130]
when i install cvxpy or  fancyimpute, always have error

error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYTHON -DCTRLC=1 -DDLONG=1 -DCOPYAMATRIX -Iscs/include -Iscs/linsys -Iscs/linsys/cpu/direct/ -Iscs/linsys/external/amd -Iscs/linsys/external/dqlql -IC:\Anaconda3\lib\site-packages\numpy\core\include -IC:\Anaconda3\include -IC:\Anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um /Tcsrc/scsmodule.c /Fobuild\temp.win-amd64-3.6\Release\src/scsmodule.obj -O3" failed with exit status 2

**Comment by sergeyf** [comment]
Ah yes that can happen. There's not much we can do for CVXPY errors unfortunately. I recommend opening a ticket on their Github repo.
