### ISSUE TITLE
References for iterative_svd

### ISSUE THREAD

**Issue by fwmeng88** [iskandr/fancyimpute#133]
Thank you for making such a nice package!

Can anyone help tell me which is the original paper for `iterative_svd`? Except the one that's mentioned, Should be similar to SVDimpute from Missing value estimation methods for DNA microarrays by Troyanskaya et. al.

My guesses are

1. M. Fuentes, P. Guttorp, and P. D. Sampson. (2006) **_Using Transforms to Analyze Space-Time Processes in Statistical methods for spatio-temporal systems_** 77-150.
2. _**A Method of Estimation of Missing Values in Multivariate Data Suitable for use with an Electronic Computer**_ S. F. Buck Journal of the Royal Statistical Society. Series B (Methodological) Vol. 22, No. 2 (1960), pp. 302-306

But not sure if I am right.

Thank you!

**Comment by sergeyf** [comment]
Thanks for the kind words!

@iskandr implemented that one. Alex - what's the reference? Is it just crappier SoftImpute?

**Comment by fwmeng88** [comment]
Thank you! @sergeyf 

I think it would be good for me to understand the math and algorithm before I start using it for my own research.

**Comment by sergeyf** [comment]
OK I think our SVD imputation is a implementation of R's svdImpute: https://rdrr.io/bioc/pcaMethods/man/svdImpute.html

And so the reference is: 

Troyanskaya O. and Cantor M. and Sherlock G. and Brown P. and Hastie T. and Tibshirani R. and Botstein D. and Altman RB. - Missing value estimation methods for DNA microarrays. Bioinformatics. 2001 Jun;17(6):520-5.

**Comment by fwmeng88** [comment]
Thank you so much for the solution, Sergey! 

@sergeyf
