### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Shadowwalker10** [iskandr/fancyimpute#139]
Installed fancyimpute using 
!pip install fancyimpute                 (in Google colab)

While trying to import fancyimpute, throws an error:

ImportError: cannot import name 'Layer' from 'keras.engine' (/usr/local/lib/python3.7/dist-packages/keras/engine/__init__.py)

![image](https://user-images.githubusercontent.com/34358548/122632507-f8d05d00-d0f2-11eb-9047-4a3cfff3c2aa.png)
![image](https://user-images.githubusercontent.com/34358548/122632544-1a314900-d0f3-11eb-8a28-e990e63fff98.png)

**Comment by sergeyf** [comment]
Ah it looks like our travis PyPi autoupdater failed. I just updated pypi to the fixed version: 0.6.0. Please give that one a try.

**Comment by Shadowwalker10** [comment]
Thank you for your swift response to the issue. It worked.
