### ISSUE TITLE
Is pinning all versions really needed?

### ISSUE THREAD

**Issue by chyzzqo2** [iskandr/fancyimpute#141]
#138 added very specific version pins for all dependencies. This makes this package more difficult to use along side other packages that may have slightly different requirements. Would you consider relaxing some of this pins or converting to the more flexible > < notations?

**Comment by sergeyf** [comment]
Figuring out the specific pins was pretty difficult as a number of packages that fancyimpute relies on don't play nicely. If you can find a set of flexible versions that install and then run reasonably, I'd be happy to review the PR.

**Comment by sergeyf** [comment]
OK I had some time and #144 is the solution. Hopefully that's loose enough. Numpy is now the only version that I have to pin exactly to avoid issues with Tensorflow.
