### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import 

### ISSUE THREAD

**Issue by Ties93** [iskandr/fancyimpute#146]
Dear all,

When installing the package in a new environment, so all dependencies are correct (and checked), i get the following error when importing functions (KNNimpute specifically):
ImportError: numpy.core.multiarray failed to import 

The error originates in cvxpy. The problem is not only present on my own system, but checked on multiple systems.

Is there a way to resolve this?

Kind regards,

Ties

**Comment by sergeyf** [comment]
Blarp, keeping up with CVXPY is a major headache. I'll investigate this but I think it might be time to drop whatever it is that depends on it...

**Comment by sergeyf** [comment]
I just made a new environment and pip installed `fancyimpute`. Then imported KNN and imported without issue. You get the error when you do `from fancyimpute import KNN`?

**Comment by sergeyf** [comment]
Tensorflow has been removed and numpy unpinned. This should be fixed. Please reopen if not.
