### ISSUE TITLE
Does the input matrix need to be normalized?

### ISSUE THREAD

**Issue by zwtInBuaa** [iskandr/fancyimpute#153]
Does the input matrix need to be normalized?
When I use MatrixFactorization() with the matrix without normalization(all the data in this matrix are lower than 1000.0), it just shows the problem:
<img width="1241" alt="截屏2023-12-07 02 19 55" src="https://github.com/iskandr/fancyimpute/assets/92677800/8e02d0d0-dc2b-4812-afdb-4731f108a6cb">
what should I do to solve this problem?

**Comment by djx99** [comment]
Hi,  did you fix it?

**Comment by sergeyf** [comment]
Sorry, we are only fixing bugs. This is not a bug. It's inconvenient, but not a bug. You can normalize yourself with one of these: https://github.com/iskandr/fancyimpute/blob/master/fancyimpute/scaler.py
