### ISSUE TITLE
No global variable called "warnings"

### ISSUE THREAD

**Issue by whigh** [iskandr/fancyimpute#45]
https://github.com/iskandr/fancyimpute/blob/18aeda9f8b0bf512dc364dd7a14713c297182a45/fancyimpute/knn.py#L106

Did you mean to set self.warnings in __init__?

**Comment by sergeyf** [comment]
Yup, thank you. I'm just going to go ahead and change it to use `self.verbose` and get rid of `warnings` entirely.

**Comment by sergeyf** [comment]
Merged!
