### ISSUE TITLE
Can you give a more detailed demo with real data?

### ISSUE THREAD

**Issue by Jayhello** [iskandr/fancyimpute#48]
Hello,Can you give a more detailed demo with real data? 

You demo in readme, and test, had no real data of knn imputation?

can you give a real data processing example? So the others may understand the package more deeply.

**Comment by maykulkarni** [comment]
I'll create a demo using Jupyter Notebook with a Kaggle problem set and open a different PR

**Comment by sergeyf** [comment]
I'm closing this. Feel free to submit a PR whenever.
