### ISSUE TITLE
Using this as a scikit learn transformer

### ISSUE THREAD

**Issue by echo66** [iskandr/fancyimpute#51]
Greetings!

I was studying the code for MICE and noticed that the [_complete_ method](https://github.com/iskandr/fancyimpute/blob/master/fancyimpute/mice.py#L330) won't keep any parameters to estimate new incoming missing values. As such, how can you use this after the model training phase???

**Comment by sergeyf** [comment]
Howdy. Yes, this is a totally transductive implementation. That is - you have a matrix `X` and all of our algorithms complete them based only on the present values in `X`. 

There is no support for inductive mode here. You have to separately complete `X_train` and `X_test`.

However! There is a MICE PR for scikit-learn that's pretty much done - check that out instead. It should be merged soon hopefully: https://github.com/scikit-learn/scikit-learn/pull/8478
