### ISSUE TITLE
Does MICE still work with scikit regressors ? 

### ISSUE THREAD

**Issue by NicolasWoloszko** [iskandr/fancyimpute#53]
the following code bugs

```
mice=MICE(model=XGBRegressor())
mice.complete(d)
```

and returns the following error : 

`TypeError: fit() got an unexpected keyword argument 'inverse_covariance'
`

**Comment by sergeyf** [comment]
No, sorry. It currently only uses my own version of Bayesian ridge regression. MICE will soon be merged into scikit-learn, at which point it will work with any regressor that has a `return_std` keyword for the `predict` method. At that point, I will remove MICE from `fancyimpute`.
