### ISSUE TITLE
MICE: imputing categorical data

### ISSUE THREAD

**Issue by javierfs** [iskandr/fancyimpute#55]
It seems imputing categorical data (strings) is not supported by MICE(). 

I just converted categorical data to numerical by applying factorize() method to ordinal data and OneHotEncoding() to nominal data. Then it imputes values but those are not discrete. 

Is it rounding off those values to its nearest discrete unit a valid approach?

**Comment by sergeyf** [comment]
You are correct - we don't support categoricals. You can modify the code
yourself to round the one hot columns to 0/1 at end of each round.

**Comment by arose13** [comment]
Has anyone done this yet or could I do a PR on this?

**Comment by sergeyf** [comment]
If you're interested, I would recommend doing a PR in `scikit-learn`. The `MICE` implementation is now a part of master: https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/impute.py#L338

As soon as the next `scikit-learn` is released, we will remove `MICE` from `fancyimpute` and just point people there. It's a more robust and better-tested version.

**Comment by benelot** [comment]
It is not part of scikit-learn anymore, because the PR got reverted. As far as I understand, they will add it back and was removed only because of an upcoming release:
https://github.com/scikit-learn/scikit-learn/pull/11600
https://github.com/scikit-learn/scikit-learn/issues/11259
