### ISSUE TITLE
setting `verbose=False` in `MatrixFactorization` still prints out epoch details

### ISSUE THREAD

**Issue by vinay9986** [iskandr/fancyimpute#56]
On calling imputation method `MatrixFactorization` like `MatrixFactorization(verbose=False).complete(data)` still prints out the epoch details. Looks like the flag `verbose` is ignored.

**Comment by vinay9986** [comment]
Yes, will try and give you the PR sometime next week :)

**Comment by sergeyf** [comment]
This will be fixed in #76
