### ISSUE TITLE
TypeError in NuclearNormMinimization

### ISSUE THREAD

**Issue by Squared2020** [iskandr/fancyimpute#57]
Hello, in attempts to execute the Nuclear Norm example, I obtain a TypeError in the _create_objective function:

S = cvxpy.Variable(m, n, name="S")
TypeError: __init__() got multiple values for keyword argument 'name'

Typically this is a 'self' call error, but that doesn't appear to be the case here. Thoughts?

**Comment by sergeyf** [comment]
Looks like `cvxpy.Variable` has changed its syntax. It should probably be `S = cvxpy.Variable((m, n), name="S")`. We don't have requirements for our `cvxpy`, but probably should. 

Either of you willing to submit a PR that updates use of `cvxpy` to correct syntax and add a version to the requirements file? Should be very straight-forward, but it would be good to have someone with a use-case do it so we can make sure nothing is breaking.
