### ISSUE TITLE
The size of batch size as an input to the MatrixFactorization model?

### ISSUE THREAD

**Issue by Eric-mingjie** [iskandr/fancyimpute#65]
https://github.com/iskandr/fancyimpute/blob/ea56129e85718e0b5be4e2c169288b53373bc409/fancyimpute/matrix_factorization.py#L103

I think this line should be:
`batch_size=int(len(y_tr) * (1 - self.validation_frac))`?

**Comment by sergeyf** [comment]
Oh dang, thanks! I'll fix it.

**Comment by sergeyf** [comment]
There is now a new release on pypi: https://pypi.org/project/fancyimpute/
