### ISSUE TITLE
Runtimewarning: division by zero in SoftImpute

### ISSUE THREAD

**Issue by johannfaouzi** [iskandr/fancyimpute#66]
https://github.com/iskandr/fancyimpute/blob/ac23bebf341718e0ea276a2bf20d1b30ac7a1e99/fancyimpute/soft_impute.py#L99-L100

If `old_missing_values` is an array of zeros, a RuntimeWarning: division by zero is raised. This always happens at the first iteration when `init_fill_method="zero"` which is the default value.

**Comment by sergeyf** [comment]
Thanks for the report.

@iskandr this looks fairly benign?

**Comment by sergeyf** [comment]
This will be fixed in #76.
