### ISSUE TITLE
more on KNN ... 

### ISSUE THREAD

**Issue by pablo3p** [iskandr/fancyimpute#71]
Hi again,

I was also wondering if your KNN method, if this can return the index of the rows that were imputed in a table structure such as Pandas dataframe , in general.

Regards,

Pablo

**Comment by sergeyf** [comment]
You can figure out which rows are missing data before using `fancyimpute`
with something like pd.isnull and specify the row axis. Those will be the
rows that were imputed.

**Comment by pablo3p** [comment]
Ok, thanks sergery,,
I already thought about this.
I was hoping that maybe it was internally done in the KNN and possibly just return the index values.

Thanks again for your quick replies.
I really appreciate it.
