### ISSUE TITLE
could u add the Biscalar usage into README.md

### ISSUE THREAD

**Issue by liyunrui** [iskandr/fancyimpute#72]

**Comment by dunchay** [comment]
Agreed. Can't get it to work at present.

**Comment by sergeyf** [comment]
Is there an error? Can you clarify "can't get it to work" please?

**Comment by dunchay** [comment]
If i follow the usage for BiScaler similar to the other functions e.g. 
`X_filled_biscaler` = `BiScaler().complete(X_incomplete_normalized)` I get 

> AttributeError: 'BiScaler' object has no attribute 'complete'

**Comment by sergeyf** [comment]
Biscaler is not a missing value imputation algorithm. It's a way to scale the data. That's why it's not in the readme. It's used internally by SoftImpute. The docstring of Biscaler says this:

```
Iterative estimation of row and column centering/scaling
```

Feel free to make a PR that adds more documentation to make this clearer =)
