### ISSUE TITLE
Proposal: align API with sklearn -> `complete` becomes `fit_transform`

### ISSUE THREAD

**Issue by sergeyf** [iskandr/fancyimpute#77]
We currently have `complete`, but this is identical in functionality to `fit_transform`. Also, with the changeover from `MICE` to `IterativeImputer`, we will have an imputer that supports an inductive `fit`/`transform`. In my opinion it is worth changing `complete` to `fit_transform` and figure out which of our other imputers can support an inductive `fit`/`transform`. Probably at least one!

@iskandr what do you think?

**Comment by iskandr** [comment]
I think this makes sense. Every time I come back to fancyimpute, which is pretty infrequent, I've forgotten its bespoke API. Would be nice to align better with sklearn.

**Comment by sergeyf** [comment]
I'm on it, thanks.

**Comment by sergeyf** [comment]
This is done. The new version of `fancyimpute` is 0.4.0 and is now live: https://pypi.org/project/fancyimpute/
