### ISSUE TITLE
ImportError: cannot import name 'abs'

### ISSUE THREAD

**Issue by zhuangxududu** [iskandr/fancyimpute#79]
When I import KNN from fancyimpute, it arises the error

from tensorflow.python.keras._impl.keras.backend import abs
ImportError: cannot import name 'abs'

Dose this arises because of incorrect tensorflow version?

**Comment by sergeyf** [comment]
Hello. 

What happens when you just do `import tensorflow` and `import keras`. Do they import without errors?

Do you mind posting the entire error trace? I don't see `ab`s being imported from `keras` anywhere in our code.

**Comment by zhuangxududu** [comment]
> Hello.
> 
> What happens when you just do `import tensorflow` and `import keras`. Do they import without errors?
> 
> Do you mind posting the entire error trace? I don't see `ab`s being imported from `keras` anywhere in our code.

Ok, it's the problem of tensorflow. Thank you very much!
