### ISSUE TITLE
AttributeError: 'KNN' object has no attribute 'complete'

### ISSUE THREAD

**Issue by hamsterLee** [iskandr/fancyimpute#81]
THIS IS MY ERROR 
dataset.dtypes
dataset.isnull().sum()
hour=364*3*24
test_cl=dataset[0:hour]
train_cl=dataset[hour:]
train.isnull().sum()
test.isnull().sum()

Xcol =dataset.columns
Xcol=Xcol.drop('aqhi')
Ycol='aqhi'
X = train_cl.loc[:, Xcol]
Y = train_cl.loc[:, Ycol]
def standardize(s):
    return s.sub(s.min()).div((s.max() - s.min()))

Xnorm = X.apply(standardize, axis=0)
kvals = np.linspace(1, 100, 20, dtype='int64')

knn_errs = []
for k in kvals:
    knn_err = []
    Xknn = KNN(k=k, verbose=False).complete(Xnorm)
    knn_err = cross_val_score(rf, Xknn, Y, cv=24, n_jobs=-1).mean()
    
    knn_errs.append(knn_err)
    print("[KNN] Estimated RF Test Error (n = {}, k = {}, 10-fold CV): {}".format(len(Xknn), k, np.mean(knn_err)))

sns.set_style("darkgrid")
plt.plot(kvals, knn_errs)
plt.xlabel('K')
plt.ylabel('10-fold CV Error Rate')

knn_err = max(knn_errs)
k_opt = kvals[knn_errs.index(knn_err)]

Xknn = KNN(k=k_opt, verbose=False).complete(Xnorm)
Yknn = Y

print("[BEST KNN] Estimated RF Test Error (n = {}, k = {}, 10-fold CV): {}".format(len(Xknn), k_opt, np.mean(knn_err)))
Traceback (most recent call last):

  File "<ipython-input-10-8a8255ff8473>", line 39, in <module>
    Xknn = KNN(k=k, verbose=False).complete(Xnorm)

AttributeError: 'KNN' object has no attribute 'complete'

**Comment by leecheukwing** [comment]
THIS IS MY CODE
for k in kvals:
    knn_err = []
    Xknn = KNN(k=k, verbose=False).complete(Xnorm)
    knn_err = cross_val_score(rf, Xknn, Y, cv=24, n_jobs=-1).mean()

    knn_errs.append(knn_err)
    print("[KNN] Estimated RF Test Error (n = {}, k = {}, 10-fold CV): {}".format(len(Xknn), k, np.mean(knn_err)))
    
sns.set_style("darkgrid")
plt.plot(kvals, knn_errs)
plt.xlabel('K')
plt.ylabel('10-fold CV Error Rate')

knn_err = max(knn_errs)
k_opt = kvals[knn_errs.index(knn_err)]

Xknn = KNN(k=k_opt, verbose=False).complete(Xnorm)
Yknn = Y

print("[BEST KNN] Estimated RF Test Error (n = {}, k = {}, 10-fold CV): {}".format(len(Xknn), k_opt, np.mean(knn_err)))

**Comment by sergeyf** [comment]
How big is your data? Looks like it is too big for knn imputation.

If you have a train/test type of setup, I would just use `IterativeImputer`. It's the only one that can work transductively.

**Comment by sergeyf** [comment]
I don't know what your error means. Which line is it happening in?

**Comment by hamsterLee** [comment]
I change my csv file to array:X_incomplete=np.array(df.to_records().view(type=np.matrix))

Sent from Mail for Windows 10

**Comment by sergeyf** [comment]
Sorry, not sure.

**Comment by hamsterLee** [comment]
I have other problem : Why i  from fancyimpute import MICE, it said
ImportError: cannot import name 'MICE'.
Could i solve this problem?

**Comment by sergeyf** [comment]
It's called IterativeImputer now.

**Comment by nkolhe123** [comment]
In one of my python imputation problem i faced the same error AttributeError: 'KNN' object has no attribute 'complete'
replacing ".complete" with ".fit_transform" resolved issue

**Comment by sergeyf** [comment]
Yes, we have stopped using `.complete` and now use `.fit_transform` everywhere to match sklearn api.

**Comment by chetan-iit-ism** [comment]
@sergeyf: Its working. Kudos to you.
