### ISSUE TITLE
the fancyimpute needs tensorflow?

### ISSUE THREAD

**Issue by Great1414** [iskandr/fancyimpute#82]
My unix has tensorflow-cpu and tensorflow-gpu. When I use the fancyimpute, it calls error about "importerror tensorflow"
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

it means the tensorflow-gpu version is error. But I can't update this GPU version. I only use this CPU version.
So how can I solve this question? thanks!

**Comment by sergeyf** [comment]
Sorry we can't help. This is a Tensorflow question. Try their GitHub.
