### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by mattharrison** [iskandr/fancyimpute#86]
The ``transform`` function has two place holders in the string but only provides one object. Throws a TypeError

https://github.com/iskandr/fancyimpute/blob/aed8a270816718992a0434e64efd0ac274dc8b34/fancyimpute/solver.py#L224

**Comment by sergeyf** [comment]
Thanks @mattharrison. Are you up for a quick PR to fix it?
