### ISSUE TITLE
Dependent package "climate" is no longer installable

### ISSUE THREAD

**Issue by chrisgeogeek** [iskandr/fancyimpute#89]
My attempts to install fancyimpute using pip fail because no version of the "climate" dependency is found. When I search for it here, https://pypi.org/search/?q=climate, it seems it is no longer hosted for pip, which is why installation is failing. I suspect you have to modify the library so that it isn't dependent on climate.

**Comment by sergeyf** [comment]
Strange, I don't see climate in the requirements file: https://github.com/iskandr/fancyimpute/blob/master/requirements.txt

When is it trying to be installed?

**Comment by chrisgeogeek** [comment]
Nevermind! I was trying to install version 0.2.0 because I read somewhere online that that was the latest. That's what failed. I just changed the version in my .yml file to 0.4.2 and it worked fine. Thanks for your reply.

**Comment by sergeyf** [comment]
Yup!
