### ISSUE TITLE
"ImportError: DLL load failed: The specified module could not be found." (Python 3.5.6 :: Anaconda 4.1.1 (64-bit))

### ISSUE THREAD

**Issue by Nipom17** [iskandr/fancyimpute#90]
I tried running the following codes in Jupyter notebook:
< import os
import pandas as pd
import numpy as np
from fancyimpute import KNN  
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency
import seaborn as sns
from random import randrange, uniform >

I got the following errors. 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2de3e4972aaf> in <module>()
      3 import pandas as pd
      4 import numpy as np
----> 5 from fancyimpute import KNN
      6 import matplotlib.pyplot as plt
      7 from scipy.stats import chi2_contingency

~\Anaconda3\lib\site-packages\fancyimpute\__init__.py in <module>()
      1 from __future__ import absolute_import, print_function, division
      2 
----> 3 from .solver import Solver
      4 from .nuclear_norm_minimization import NuclearNormMinimization
      5 from .iterative_imputer import IterativeImputer

~\Anaconda3\lib\site-packages\fancyimpute\solver.py in <module>()
     18 from six.moves import range
     19 
---> 20 from sklearn.utils import check_array
     21 
     22 from .common import generate_random_column_samples

~\Anaconda3\lib\site-packages\sklearn\__init__.py in <module>()
     62 else:
     63     from . import __check_build
---> 64     from .base import clone
     65     from .utils._show_versions import show_versions
     66 

~\Anaconda3\lib\site-packages\sklearn\base.py in <module>()
     11 from scipy import sparse
     12 from .externals import six
---> 13 from .utils.fixes import signature
     14 from . import __version__
     15 

~\Anaconda3\lib\site-packages\sklearn\utils\__init__.py in <module>()
     11 
     12 from .murmurhash import murmurhash3_32
---> 13 from .validation import (as_float_array,
     14                          assert_all_finite,
     15                          check_random_state, column_or_1d, check_array,

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in <module>()
     20 
     21 from ..externals import six
---> 22 from ..utils.fixes import signature
     23 from .. import get_config as _get_config
     24 from ..exceptions import NonBLASDotWarning

~\Anaconda3\lib\site-packages\sklearn\utils\fixes.py in <module>()
     81             return stats.boxcox(x, lmbda)
     82 else:
---> 83     from scipy.special import boxcox  # noqa
     84 
     85 

~\Anaconda3\lib\site-packages\scipy\special\__init__.py in <module>()
    638 from .sf_error import SpecialFunctionWarning, SpecialFunctionError
    639 
--> 640 from ._ufuncs import *
    641 
    642 from .basic import *

ImportError: DLL load failed: The specified module could not be found.

Please help in this.

**Comment by sergeyf** [comment]
Sounds like your scipy install is broken. Not really a `fancyimpute` problem.
