### ISSUE TITLE
NAs of one feature are replaced with same value

### ISSUE THREAD

**Issue by Make42** [iskandr/fancyimpute#92]
When using the imputers on a 2D dataset, all NAs of one feature get replaced by the same value. I doubt this is correct and remember that version 0.1.0 imputed missing values individually. What is going on?

**Comment by sergeyf** [comment]
Do you have a code snippet to replicate this?

**Comment by Make42** [comment]
Try the following

```
import pandas as pd
import numpy as np
import fancyimpute as impute
mydata = np.array([[1.5       ,        np.nan],
       [0.        ,        np.nan],
       [       np.nan, 5.        ],
       [       np.nan, 8.        ],
       [8.        ,        np.nan],
       [       np.nan, 8.        ],
       [       np.nan, 6.        ],
       [2.5       ,        np.nan],
       [0.78175529,        np.nan],
       [9.61898081,        np.nan],
       [8.17303221,        np.nan],
       [3.99782649,        np.nan],
       [4.31413827,        np.nan],
       [2.63802917,        np.nan],
       [       np.nan, 5.79704587],
       [1.44954798,        np.nan],
       [3.50952381,        np.nan],
       [0.75966692,        np.nan],
       [       np.nan, 2.39952526],
       [       np.nan, 9.0271611 ],
       [4.90864092,        np.nan],
       [       np.nan, 3.69246781],
       [7.80252068,        np.nan],
       [       np.nan, 0.96454525],
       [9.42050591,        np.nan],
       [0.59779543,        np.nan],
       [       np.nan, 0.15403438],
       [       np.nan, 6.49115475],
       [6.47745963,        np.nan],
       [2.96320806,        np.nan],
       [6.86775433,        np.nan],
       [6.25618561,        np.nan],
       [       np.nan, 7.75712679],
       [4.35858589,        np.nan],
       [5.08508655,        np.nan],
       [7.94831417,        np.nan],
       [8.11580458,        np.nan],
       [9.39001562,        np.nan],
       [       np.nan, 5.87044705],
       [3.0124633 ,        np.nan],
       [       np.nan, 1.9476429 ],
       [1.70708047,        np.nan],
       [       np.nan, 9.23379642],
       [       np.nan, 9.04880969],
       [4.38869973,        np.nan],
       [4.08719846,        np.nan],
       [       np.nan, 7.1121578 ],
       [       np.nan, 2.96675873],
       [       np.nan, 5.07858285],
       [       np.nan, 8.01014623],
       [9.28854139,        np.nan],
       [       np.nan, 2.3728358 ],
       [       np.nan, 5.46805719],
       [2.31594387,        np.nan],
       [6.79135541,        np.nan],
       [9.87982003,        np.nan],
       [9.13286828,        np.nan],
       [       np.nan, 3.3535684 ],
       [       np.nan, 7.21227499],
       [6.53757349,        np.nan],
       [7.15037078,        np.nan],
       [3.34163053,        np.nan],
       [0.30540946,        np.nan],
       [4.79922141,        np.nan],
       [6.1766639 ,        np.nan],
       [5.76721516,        np.nan],
       [       np.nan, 0.28674152],
       [       np.nan, 9.7868065 ],
       [       np.nan, 4.71088375],
       [6.81971904,        np.nan],
       [       np.nan, 0.96730026],
       [8.17547092,        np.nan],
       [       np.nan, 5.18594943],
       [       np.nan, 8.00330575],
       [4.32391504,        np.nan],
       [       np.nan, 1.73388613],
       [8.31379743,        np.nan],
       [       np.nan, 5.26875831],
       [6.56859891,        np.nan],
       [4.3165117 ,        np.nan],
       [       np.nan, 1.06216345],
       [1.98118403,        np.nan],
       [       np.nan, 9.2033204 ],
       [7.37858096,        np.nan],
       [5.47870901,        np.nan],
       [9.83052466,        np.nan],
       [       np.nan, 5.39126465],
       [       np.nan, 1.78132454],
       [9.99080395,        np.nan],
       [5.61199793,        np.nan],
       [       np.nan, 3.68916546],
       [9.81637951,        np.nan],
       [       np.nan, 3.7627221 ],
       [4.28252993,        np.nan],
       [       np.nan, 2.2618768 ],
       [5.82986383,        np.nan],
       [       np.nan, 2.6528091 ],
       [       np.nan, 7.30248792],
       [       np.nan, 1.07769015],
       [       np.nan, 8.17760559]])
data_completed = impute.IterativeImputer().fit_transform(mydata)
```

**Comment by sergeyf** [comment]
Ah I think I know what's going on. `IterativeImputer` tries to impute missing values in each column/feature from known values in all the other columns. What you have there is a particular example where that's impossible - there is not a single row that has both columns non-nan. So there is no way to learn a model from X1_known to X2_missing and vice versa. If you, for example, change the first row to `[1.5       ,        1.5]` it will suddenly start doing something. As is, it's just giving you the initial imputation and then failing to iteratively impute further.

So this isn't a bug. I'll close the issue, but feel free to chat further if you'd like.

**Comment by Make42** [comment]
MICE in fancyimpute 0.1.0 was able to handle this dataset though... why?

Does that mean that iterative imputation is not able to handle datasets in which per row each value (but one) is missing?

**Comment by sergeyf** [comment]
I am not sure why an earlier version was able to handle it. It doesn't make sense for it to have when thinking about how `IterativeImputer` works. I probably won't make time to investigate this oddity. By the way, there is now a more developed, bugless version of `IterativeImputer` in the scikit-learn master. I suspect it will behave the same as `fancyimpute`'s but you should give it a try.

`Does that mean that iterative imputation is not able to handle datasets in which per row each value (but one) is missing?` I think that's true. It needs some examples (rows) where more than one sample is NOT missing so it can learn a function between them. 

The kind of dataset you describe will probably be very hard to impute in any case. I can't think of a way to do it at all that's reasonable.

**Comment by Make42** [comment]
I think I understand what you mean.

**Comment by Make42** [comment]
After looking into it some more I have doubt in your answer after all:

In the video https://www.youtube.com/watch?v=zX-pacwVyvU I noticed that the first missing values are first imputed with an initial impute. The following iterative linear models are fit on those. Thus it should not matter that all but one value is missing for each row in my dataset.

Then I noticed that in both the old version and  the new version, it is possible to say what this initial impute is supposed to be (parameter `initial_strategy` for the current, `init_fill_method` for the old version).

Finally I noticed that if I use a pandas DataFrame as mydata (as I did before) I do not get results. While the code in my question uses a numpy array, the code in my IDE actually uses a pandas DataFrame instead. With this DataFrame I do not get a properly filled new dataset. However, if I use a numpy array, I do get a properly filled dataset. My legacy code for the old fancyimpute version did indeed use the `.values` member of the respective DataFrame, which I missed when transporting my legacy code to the new experiments.

Thus I guess the answer should actually be that there is no issue with the algorithm, but that I should simply make sure to use a numpy array instead of a DataFrame.

**Comment by sergeyf** [comment]
Yes, it's true that there is an initial imputation. But it imputes a
constant value for all of them. Then when you do PREDICT, you end up with
the exact same output because the inputs are all the result of the initial
imputation (constant).

**Comment by Make42** [comment]
Ah, because of the same value for each of outputs (the mean), I get a regression without a slope and only an intercept for the models and thus it stays this way?

**Comment by sergeyf** [comment]
Yes. I think so.
